### ISSUE TITLE
Create junits for all archetypes and targets in standalone Maven environment

### ISSUE THREAD

**Issue by cbridgha** [WASdev/ci.maven.tools#1]
We can use the ci.maven project tests as an example.   

Archetype tests should call each archetype to create project, and test if project was properly created.
These tests should pass in standalone maven environments.

Target runtime pom tests should ensure all dependencies can be resolved

**Comment by rea-al** [comment]
There were created simple tests to verify project generation and compilation with the archetypes using org.apache.maven.plugins:maven-archetype-plugin:2.4:integration-test plugin that it's invoked by the default life-cycle of the maven-archetype package.

Tests depends of the presence of the target poms due that projects generated with archetypes reference them to gather all WebSphere Liberty APIs.

Closing this issue as this is solved. Reopen if needed.
